--- 
- hosts: 172.31.16.245 
  become: yes
  tasks:
     - name: i want to execute linux command
       command: hostname -f
       register: myresult

     - name: i want to display linux output 
       debug:
         msg: "{{myresult}}"

     - name: i want to install apache2
       apt:
          name: apache2 
          state: present 
       when: myresult.stderr ==""

     - name: i want to install git
       apt:
          name: git
          state: present 
       when: myresult.stderr !=""